DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
COPY_PHASE_STRIP: 'NO'
ENABLE_NS_ASSERTIONS: 'NO'
GCC_OPTIMIZATION_LEVEL: s
VALIDATE_PRODUCT: 'YES'
CLANG_WARN_SUSPICIOUS_MOVE: 'YES'
