DEBUG_INFORMATION_FORMAT: dwarf
SWIFT_OPTIMIZATION_LEVEL: "-Onone"
ENABLE_TESTABILITY: 'YES'
GCC_DYNAMIC_NO_PIC: 'NO'
GCC_OPTIMIZATION_LEVEL: '0'
ONLY_ACTIVE_ARCH: 'YES'
SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
CLANG_WARN_SUSPICIOUS_MOVE: 'YES'
MTL_ENABLE_DEBUG_INFO: 'YES'
GCC_PREPROCESSOR_DEFINITIONS:
- DEBUG=1
- "$(inherited)"
