name: CI
on: [push, pull_request]
jobs:
  test_swift_5:
    runs-on: macos-latest
    #name: Test Swift 5
    steps:
    - uses: actions/checkout@master
    #- name: Xcode version
    #  run: sudo xcode-select -s /Applications/Xcode_11_beta.app
    - name: Info
      run: |
        swift --version
        swift package --version
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build
    - name: Test
      run: swift test
    - name: Gen fixtures
      run: scripts/gen-fixtures.sh
    - name: Check fixtures
      run: scripts/diff-fixtures.sh
    - name: Build fixtures
      run: scripts/build-fixtures.sh
    - name: Build release
      run: make build
  
