name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    name: Test ${{ matrix.xcode_version }}
    strategy:
      matrix:
        xcode_version: ['10.3', '11_beta']
    steps:
    - uses: actions/checkout@master
    - name: Info
      run: |
        swift --version
        swift package --version
        xcode-select -p
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build
    - name: Test
      run: swift test
    - name: Gen fixtures
      run: scripts/gen-fixtures.sh
    - name: Check fixtures
      run: scripts/diff-fixtures.sh
    - name: Build fixtures
      run: scripts/build-fixtures.sh
    - name: Build release
      run: make build
  
